### ISSUE TITLE
firefox 6dof @November 9 version access a Mozilla hubs web page，no controller in the view  -- high priority

### ISSUE THREAD

**Issue by dingsing2021** [hms-ecosystem/OpenXR-SDK#20]
The handle cannot be seen in the field of view. This problem is reported by our colleagues in Germany. so please visit this website and make sure the handle works properly.
here is the web address：
https://xrhubspace.de/bPA7XDe/xr-spaces-main-lobby  
https://xrhubspace.de/XiKCzTK/summit-hub

**Comment by fwei-io** [comment]
![image](https://user-images.githubusercontent.com/57159719/141384791-77eeca19-898c-4dc9-9649-648b7486b6e0.png)

**Comment by fwei-io** [comment]
@MortimerGoro to investigate this issue.

**Comment by MortimerGoro** [comment]
Controllers work in https://hubs.mozilla.com/

Is xrhubspace.de using an older version of mozilla hubs?

**Comment by MortimerGoro** [comment]
I have asked about this to a Hubs developer. The code is minified so hard to know the difference between both versions of hubs

**Comment by MortimerGoro** [comment]
I looked into this issue in more detail and I found the problem:
xrhubspace.de is using a old Hubs version that combines WebVR (old spec) and WebXR (new spec), and tries to use WebVR with Firefox Reality. The OpenXR build is using the interaction profiles instead of setting the deprecated controller names used for WebVR. I had to do some workarounds with the User Agent and Gecko preferences to force it to run the WebXR version.

You can test it on the v13 demo uploaded today

**Comment by MortimerGoro** [comment]
For reference I created this Gecko patch: https://bugzilla.mozilla.org/show_bug.cgi?id=1742430

It will also require a FxR patch. I'll post it.

**Comment by fwei-io** [comment]
It is working in xrhubspace.de now, thank you.
